php: 
- 5.3
- 5.4
- 5.5
env: 
  global: 
    secure: X13ROdPWdEN/1l596zKm/Pqz1ACB/rExIRrqnRKnuetB+chiMKL+aQplgK5QMxU9Zr0+z8XdCrOjymHzpLUcCRSzyOddlDPw7S72KNvN9D+xHY47B7X5LRWd4RtNXpFbHKHYa1huP7ORe2lCTdvlL5GPO0PkNCnpSl6iM8gjWjM=
language: php
before_script: composer install --dev
