env: 
  secure: Cq5ZtE0WhZrD3kZf68JNARPqpuqxVZcLV4qs1lOZn6ktMT1m1q4eyOwll56nzQjZKXA0tx4LhrJ1BfzA3riUynSOAhSRoANuWEExcphtlYuNltCBUZhc1L9I80apA+14pAewTcdCe6G8Mzvi2rJFYWrkRQI6gARwPzaRz1G2dvk=
language: php
before_script: composer install --dev
php: 
- 5.3
- 5.4
- 5.5
