php: 
- 5.3
- 5.4
- 5.5
before_script: composer install --dev
language: php
env: 
  secure: gN+kyYf2zRLaDul+kPLhffGF3hINgABtZzpqH1sdTCo6pSI0PCr704ziT5AZ/WEj+qF4WreX4CIkzbQ3zD1d63XQNZ8z9UXmCYHkLQrrEjfhs5OME2z1Pw2DY+70Xl/R2arLrvADY5XHXhKT57MvQP54fTmnbCj/b0GhBvzr5hU=
